// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetsRegApi.Models;

namespace PetsRegApi.Migrations
{
    [DbContext(typeof(PetsDBContext))]
    [Migration("20210711075230_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetsRegApi.Models.PetInfo", b =>
                {
                    b.Property<int>("petId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("petName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("species")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("petId");

                    b.ToTable("PetsList");
                });
#pragma warning restore 612, 618
        }
    }
}
